### ISSUE TITLE
MVCのmodelにあたる部分を作成

### ISSUE THREAD

**Issue by s-usukura** [koshikita-volleyball/turnip#221]
サーバーサイドでデータを読み込むライブラリを作成する

**Comment by osawa-koki** [comment]
不要と判断。
DynamoDBでクエリ発行時に指定した方が柔軟性が確保できるため。

**Comment by s-usukura** [comment]
DynamoDBの`prices-daily-quotes`はデータ量が大きいため、PKやソートキーを使って検索しなければならない。
これを毎回考えるのは大変なため、やっぱりmodelを用意する。
