### ISSUE TITLE
銘柄一覧取得APIがローカルだと動くが、本番だと動かない。

### ISSUE THREAD

**Issue by osawa-koki** [koshikita-volleyball/turnip#68]
Link #66 #67

**Comment by osawa-koki** [comment]
考えたこと

- 実行時間
- メモリサイズ

いずれも確認済み。
特に問題はなかった。

**Comment by osawa-koki** [comment]
まずは、レスポンスデータが大きすぎることが原因と疑って、自分で作成したダミーデータを返して確認してみる。
これで動作する場合には、メモリの上限 or レスポンスサイズの上限を確認する。

※ レスポンスサイズの上限があるかどうかは要確認。

**Comment by osawa-koki** [comment]
ステータスコードは200で、問題なし。
catch句にも入っていないため、正常に実行終了されていると思われる。

どの段階でエラーが起きている or 起きていない？かを確認する！

**Comment by osawa-koki** [comment]
サイズが上限であることを想定すると、株価四本値のコードと日付を指定したAPIを先に実装した方がいいかもしれない。
※ データサイズが比較的小さいから。

**Comment by osawa-koki** [comment]
@s-usukura くん。

協力お願いします！！！

**Comment by s-usukura** [comment]
GetRefreshTokenの関数にawaitを付けたら解決！
